/**
 * Hebrew + English synonyms keyed by backbone leaf id.
 *
 * Each list is matched against a normalized chain category name. Any token
 * substring match counts as a hit; the matcher in `match.ts` ranks leaves by
 * how many distinct synonyms hit and how specific the longest hit was.
 *
 * Tips when extending:
 *   - Use the SHORTEST distinguishing prefix (Hebrew lacks word stemming so
 *     "גבינ" matches "גבינה", "גבינות", "גבינת" all at once).
 *   - Order matters for tie-breaking: put the strongest discriminators first.
 *   - Avoid overly generic words ("מוצרי", "חלבי") — they live in
 *     STOP_WORDS in `similarity.ts`.
 */

export const LEAF_SYNONYMS: Readonly<Record<string, readonly string[]>> = {
  // --- dairy ---
  'dairy/milk': ['חלב טרי', 'חלב מפוסטר', 'חלב', 'milk', 'שוקו'],
  'dairy/cheese': [
    'גבינ',
    'גבינה צהובה',
    'גבינת',
    'cheese',
    'מוצרלה',
    'פטה',
    'בולגרית',
    'קממבר',
    'ברי',
    'פרמזן',
    'מסקרפונה',
    'קוטג',
  ],
  'dairy/yogurt': [
    'יוגורט',
    'מעדן',
    'מעדנים',
    'דניאלה',
    'דנונה',
    'אקטימל',
    'yog',
    'pudding',
    'קפיר',
    'kefir',
    'אשל',
    'פרי-גן',
  ],
  'dairy/eggs': ['ביצי', 'ביצים', 'eggs', 'egg'],
  'dairy/butter-cream': [
    'חמאה',
    'butter',
    'שמנת',
    'cream',
    'sour cream',
    'cooking cream',
    'מסקרפונה',
    'קצפת',
    'whipping',
  ],
  'dairy/plant-based': [
    'משקה שקדים',
    'משקה סויה',
    'משקה שיבולת',
    'חלב סויה',
    'חלב שקדים',
    'חלב שיבולת',
    'almond milk',
    'soy milk',
    'oat milk',
    'plant-based',
    'vegan',
    'טבעוני',
    'צמחי',
  ],
  // --- produce ---
  'produce/vegetables': [
    'ירק',
    'ירקות',
    'עגבני',
    'מלפפון',
    'בצל',
    'תפוח אדמה',
    'תפו"א',
    'גזר',
    'פלפל',
    'חס',
    'כרוב',
    'ברוקולי',
    'קישוא',
    'חציל',
    'דלעת',
    'vegetable',
    'tomato',
    'cucumber',
    'onion',
    'potato',
    'carrot',
    'lettuce',
    'cabbage',
    'broccoli',
    'eggplant',
  ],
  'produce/fruits': [
    'פרי',
    'פירות',
    'פיר ',
    'תפוח',
    'בננה',
    'תפוז',
    'אבוקדו',
    'תות',
    'ענב',
    'אבטיח',
    'מלון',
    'אגס',
    'נקטרינה',
    'אפרסק',
    'fruit',
    'apple',
    'banana',
    'orange',
    'avocado',
    'grape',
    'watermelon',
    'melon',
    'pear',
    'peach',
    'mango',
    'pineapple',
    'strawberry',
  ],
  'produce/herbs': [
    'עשבי תיבול',
    'תיבול טרי',
    'פטרוזיליה',
    'כוסברה',
    'בזיליקום',
    'נענע',
    'שמיר',
    'רוזמרין',
    'תימין',
    'herbs',
    'parsley',
    'cilantro',
    'basil',
    'mint',
    'dill',
    'rosemary',
    'thyme',
  ],
  'produce/organic': ['אורגני', 'organic', 'bio', 'שופרסל גרין', 'גרין', 'בריאות וטבע', 'תוספי מזון'],
  // --- bakery ---
  'bakery/bread': ['לחם', 'baguette', 'בגט', 'bread', 'loaf'],
  'bakery/pita-challah': ['פיתה', 'פיתות', 'חלה', 'בייגל', 'bagel', 'challah', 'pita'],
  'bakery/pastries': [
    'מאפה',
    'מאפי',
    'בורקס',
    'קרואסון',
    'עוגה',
    'עוגי',
    'מאפים',
    'pastry',
    'cake',
    'croissant',
    'bourekas',
  ],
  // --- breakfast ---
  'breakfast/cereals': [
    'דגני בוקר',
    'קורנפלקס',
    'גרנולה',
    'מוזלי',
    'שיבולת שועל',
    'cornflakes',
    'cereal',
    'granola',
    'oats',
    'oatmeal',
    'muesli',
    'cheerios',
  ],
  'breakfast/spreads': [
    'ממרח',
    'ממרחים',
    'ריבה',
    'נוטלה',
    'חמאת בוטנים',
    'שוקולד למריחה',
    'jam',
    'spread',
    'nutella',
    'peanut butter',
  ],
  'breakfast/honey': ['דבש', 'סילאן', 'סירופ מייפל', 'honey', 'maple', 'silan', 'date syrup'],
  // --- meat / fish ---
  'meat-fish/beef': [
    'בקר',
    'טלה',
    'כבש',
    'המבורגר',
    'אנטריקוט',
    'סינטה',
    'בשרים על האש',
    'בשר על האש',
    'מנגל',
    'beef',
    'lamb',
    'burger',
    'steak',
    'mince',
    'ground meat',
    'bbq',
  ],
  'meat-fish/poultry': [
    'עוף',
    'הודו',
    'שוק עוף',
    'חזה עוף',
    'כנפיים',
    'קציצ',
    'שניצל',
    'poultry',
    'chicken',
    'turkey',
    'schnitzel',
    'wing',
  ],
  'meat-fish/fish': [
    'דגים',
    'סלמון',
    'טונה',
    'דניס',
    'בקלה',
    'סרדינים',
    'אנשובי',
    'fish',
    'salmon',
    'tuna',
    'cod',
    'sardine',
    'anchovy',
  ],
  'meat-fish/deli': [
    'נקני',
    'נקניק',
    'נקניקיות',
    'פסטרמ',
    'סלמ',
    'frankfurter',
    'sausage',
    'salami',
    'pastrami',
    'hot dog',
    'frankfurter',
  ],
  // --- frozen ---
  'frozen/meals': [
    'ארוחה קפואה',
    'ארוחות קפואות',
    'פיצה קפואה',
    'frozen meal',
    'pizza',
    'מאפים קפואים',
  ],
  'frozen/ice-cream': ['גלידה', 'ארטיק', 'שלגון', 'ice cream', 'gelato', 'sorbet'],
  'frozen/vegetables': ['ירקות קפואים', 'אפונה קפואה', 'frozen vegetables', 'frozen peas'],
  'frozen/fish': ['דגים קפואים', 'frozen fish'],
  // --- pantry ---
  'pantry/grains': [
    'אורז',
    'פסטה',
    'נודלס',
    'בורגול',
    'קוסקוס',
    'rice',
    'pasta',
    'noodle',
    'couscous',
    'spaghetti',
  ],
  'pantry/oils': ['שמן זית', 'שמן קנולה', 'שמן חמניות', 'שמן', 'oil', 'olive oil', 'canola'],
  'pantry/flour-sugar': [
    'קמח',
    'סוכר',
    'אבקת אפיה',
    'שמרים',
    'flour',
    'sugar',
    'baking',
    'yeast',
    'powdered sugar',
  ],
  'pantry/spices': [
    'תבלין',
    'מלח',
    'פלפל שחור',
    'פפריקה',
    'כמון',
    'פרג',
    'spice',
    'salt',
    'pepper',
    'paprika',
    'cumin',
  ],
  'pantry/sauces': [
    'רוטב',
    'קטשופ',
    'מיונז',
    'חרדל',
    'חומץ',
    'סויה',
    'sauce',
    'ketchup',
    'mayonnaise',
    'mustard',
    'vinegar',
    'soy sauce',
  ],
  'pantry/canned': [
    'שימור',
    'שימורי',
    'תירס משומר',
    'אפונה משומרת',
    'תירס',
    'שעועית',
    'canned',
    'preserves',
    'corn',
  ],
  'pantry/legumes': [
    'קטניות',
    'עדשים',
    'גרגרי חומוס',
    'שעועית יבשה',
    'מאש',
    'lentils',
    'chickpeas',
    'beans',
    'kidney',
  ],
  'pantry/middle-eastern': ['טחינה', 'חומוס', 'אמבה', 'tahini', 'hummus', 'amba'],
  // --- snacks / sweets ---
  'snacks/salty': [
    'חטיף',
    'חטיפים',
    'במבה',
    'ביסלי',
    "צ'יפס",
    'תפוצ',
    'פופקורן',
    'פיצוחים',
    'crisps',
    'chips',
    'popcorn',
    'pretzel',
  ],
  'snacks/chocolate': [
    'שוקולד',
    'פרלינים',
    'טבלת שוקולד',
    "kit kat",
    "snickers",
    "mars",
    'chocolate',
    'praline',
  ],
  'snacks/candy': ['סוכריות', 'גומי', 'מנטוס', 'candy', 'gummy', 'jelly', 'mint'],
  'snacks/cookies': [
    'עוגיות',
    'ביסקויט',
    'ופל',
    'קרקר',
    'cookie',
    'biscuit',
    'wafer',
    'cracker',
  ],
  'snacks/dried-fruit': [
    'פירות יבשים',
    'אגוזים',
    'בוטנים',
    'שקדים',
    'קשיו',
    'פיסטוק',
    'תאנים',
    'תמרים',
    'צימוקים',
    'פיצוחים',
    'almond',
    'cashew',
    'pistachio',
    'raisin',
    'date',
    'fig',
    'nuts',
  ],
  // --- beverages ---
  'beverages/water': ['מים מינרל', 'מים', 'נביעות', 'mineral water', 'spring water', 'sparkling'],
  'beverages/soft': [
    'משקאות קלים',
    'משק קל',
    'קולה',
    'פפסי',
    'ספרייט',
    'פנטה',
    'soft drink',
    'cola',
    'pepsi',
    'sprite',
    'fanta',
    'soda',
  ],
  'beverages/juice': [
    'מיץ',
    'תפוזינה',
    'משק פרי',
    'תרכיז',
    'תרכיזים',
    'juice',
    'orange juice',
    'apple juice',
    'concentrate',
    'syrup',
  ],
  'beverages/coffee-tea': [
    'קפה',
    'תה',
    'נס קפה',
    'אספרסו',
    'קפה נמס',
    'משקאות חמים',
    'משקה חם',
    'cappuccino',
    'coffee',
    'tea',
    'espresso',
    'instant coffee',
    'hot drink',
  ],
  'beverages/energy': [
    'משקה אנרגיה',
    'אנרגיה',
    'red bull',
    'monster',
    'xl',
    'energy drink',
    'isotonic',
  ],
  // --- alcohol ---
  'alcohol/beer': ['בירה', 'beer', 'lager', 'ale'],
  'alcohol/wine': ['יין', 'wine', 'cabernet', 'merlot', 'chardonnay', 'sauvignon'],
  'alcohol/spirits': [
    'וודקה',
    'ויסקי',
    'ערק',
    'גין',
    'רום',
    'טקילה',
    'ליקר',
    'spirits',
    'vodka',
    'whiskey',
    'whisky',
    'gin',
    'rum',
    'tequila',
    'liqueur',
    'arak',
    'cognac',
  ],
  // --- baby ---
  'baby/diapers': ['חיתול', 'חיתולים', 'diaper', 'pampers', 'huggies', 'libero'],
  'baby/formula-food': [
    'פורמולה',
    'מטרנה',
    'סימילאק',
    'נוטרילון',
    'מחית',
    'תחליף חלב',
    'מזון לתינוק',
    'אוכל לתינוק',
    'מזון לתינוקות',
    'formula',
    'baby food',
    'puree',
    'similac',
    'enfamil',
  ],
  'baby/wipes': ['מגבונים לתינוק', 'מגבונ', 'wipes', 'baby wipes'],
  'baby/care': [
    'טיפוח תינוק',
    'אביזרי תינוק',
    'מוצרי ילדים',
    'מוצרי תינוק',
    'baby care',
    'baby accessories',
  ],
  // --- household ---
  'household/cleaning': [
    'ניקוי',
    'ניקיון',
    'חומר ניקוי',
    'אקונומיקה',
    'מלבין',
    'קוטל חרקים',
    'מבשם אויר',
    'מבשמי אויר',
    'cleaning',
    'detergent',
    'bleach',
    'disinfectant',
    'multi-surface',
    'air freshener',
    'insecticide',
  ],
  'household/paper': [
    'נייר טואלט',
    'מגבת נייר',
    'טישו',
    'מפיות',
    'toilet paper',
    'paper towel',
    'tissue',
    'napkin',
    'kleenex',
  ],
  'household/laundry': [
    'כביסה',
    'אבקת כביסה',
    'מרכך כביסה',
    'חדר כביסה',
    'אמבטיה וחדר כביסה',
    'laundry',
    'detergent',
    'fabric softener',
    'persil',
    'ariel',
  ],
  'household/kitchen': [
    'כלי בית',
    'כלי מטבח',
    'חד פעמי',
    'אלומיניום',
    'נייר אפיה',
    'baking paper',
    'aluminum',
    'cling film',
    'kitchenware',
    'household',
  ],
  // --- personal-care ---
  'personal-care/toiletries': [
    'סבון',
    'שמפו',
    'מרכך שיער',
    'גוף',
    'soap',
    'shampoo',
    'conditioner',
    'body wash',
    'shower gel',
    'דאודורנט',
    'deodorant',
  ],
  'personal-care/cosmetics': [
    'איפור',
    'מסקרה',
    'שפתון',
    'מייקאפ',
    'אודם',
    'בושם',
    'lipstick',
    'mascara',
    'foundation',
    'cosmetic',
    'perfume',
    'בושם',
  ],
  'personal-care/oral': [
    'משחת שיניים',
    'מברשת שיניים',
    'מי פה',
    'שטיפת פה',
    'היגיינת הפה',
    'היגיינה אוראלית',
    'toothpaste',
    'toothbrush',
    'mouthwash',
    'oral',
    'dental',
  ],
  'personal-care/shaving': [
    'גילוח',
    'מכונת גילוח',
    'סכין גילוח',
    'אחרי גילוח',
    'הסרת שיער',
    'שעוות',
    'shaver',
    'razor',
    'shaving',
    'after shave',
    'wax',
    'hair removal',
  ],
  'personal-care/feminine': [
    'תחבושות',
    'טמפונים',
    'היגיינה נשית',
    'pads',
    'tampons',
    'feminine hygiene',
    'always',
    'tampax',
  ],
  // --- pet ---
  'pet/dog': ['כלב', 'כלבים', 'מזון לכלבים', 'מזון יבש לכלב', 'dog food', 'pedigree', 'royal canin'],
  'pet/cat': ['חתול', 'חתולים', 'מזון לחתולים', 'cat food', 'whiskas', 'kitten'],
};

/**
 * Group-level synonyms — used as a *fallback* when no leaf scores high
 * enough. Lets generic chain categories like "קפואים" (Frozen) map onto a
 * backbone GROUP id even when no specific leaf is a clear winner.
 */
export const GROUP_SYNONYMS: Readonly<Record<string, readonly string[]>> = {
  dairy: ['מוצרי חלב', 'חלב ומוצרי חלב', 'חלבי', 'dairy'],
  produce: ['פירות וירקות', 'ירקות ופירות', 'produce'],
  bakery: ['מאפיה', 'מאפים', 'bakery'],
  breakfast: ['ארוחת בוקר', 'דגנים', 'breakfast'],
  'meat-fish': ['בשר ודגים', 'בשר ועוף', 'בשרים', 'דגים', 'meat', 'fish'],
  frozen: ['קפוא', 'קפואים', 'מוצרים קפואים', 'frozen'],
  pantry: [
    'מזווה',
    'יסודות מטבח',
    'יסודות',
    'מצרכי יסוד',
    'pantry',
    'staples',
  ],
  snacks: ['חטיפים', 'ממתקים', 'חטיפים וממתקים', 'snacks', 'sweets'],
  beverages: ['משקאות', 'משק קלים', 'beverages', 'drinks'],
  alcohol: ['אלכוהול', 'משקאות חריפים', 'יין ואלכוהול', 'alcohol'],
  baby: [
    'תינוקות',
    'מוצרי תינוקות',
    'פארם ותינוקות',
    'תינוקות וילדים',
    'baby',
  ],
  household: [
    'ניקיון',
    'בית וניקיון',
    'הכל לבית',
    'אחזקת הבית',
    'אחזקת בית',
    'household',
  ],
  'personal-care': [
    'טיפוח',
    'טיפוח ויופי',
    'מוצרי פארם',
    'פארם',
    'קוסמטיקה',
    'personal care',
    'pharm',
  ],
  pet: ['חיות מחמד', 'בעלי חיים', 'בע"ח', 'pet'],
};

/**
 * Stop-words/phrases that appear in MANY chain category names but tell us
 * nothing about which leaf they belong to. We strip these before scoring.
 */
export const STOP_WORDS: ReadonlyArray<string> = [
  'מוצרי',
  'מוצר',
  'מותגים',
  'מותג',
  'בלעדי',
  'מבצעים',
  'מבצע',
  'חדש',
  'מומלץ',
  'אונליין',
  'תוצרת',
  'תוצרת חוץ',
  'תוצרת ישראל',
  'ל-',
  'ולל',
  'ולא',
  'מארז',
  'מארזים',
  'מבחר',
  'מבחר רחב',
  'הכל',
];
