/**
 * Hebrew + English synonyms keyed by backbone node id.
 *
 * The keys here target the 3-depth backbone (`packages/ingestion/src/category-
 * mapper/backbone.ts`). A key may name a department, a category, or a sub-
 * category — anything that exists in `COMMON_BY_ID`. The matcher in
 * `similarity.ts` uses these lists as a fallback when the chainHints layer
 * doesn't have a direct binding, and `refine.ts` consults them to corroborate
 * a chain alias against the product's own name.
 *
 * Tips when extending:
 *   - Use the SHORTEST distinguishing prefix (Hebrew lacks word stemming so
 *     "גבינ" matches "גבינה", "גבינות", "גבינת" all at once).
 *   - Order matters for tie-breaking: put the strongest discriminators first.
 *   - Avoid overly generic words ("מוצרי", "חלבי") — they live in
 *     STOP_WORDS in `similarity.ts`.
 */

export const LEAF_SYNONYMS: Readonly<Record<string, readonly string[]>> = {
  // --- dairy ---
  //
  // Generic "חלב" without a qualifier defaults to fresh cow milk in Hebrew,
  // so unqualified milk synonyms key the `dairy/milk/fresh` terminal
  // directly (plant-based and UHT terms live on `dairy/milk/alternatives`,
  // ready-to-drink milk + protein drinks live on `dairy/milk/drinks`).
  // Generic cheese terms key the `/general` fallback leaf — when the chain
  // alias already picked a specific cheese sub-type, the refine pass keeps
  // that more specific alias instead of demoting to /general (see refine.ts
  // step 5).
  'dairy/milk/fresh': ['חלב טרי', 'חלב מפוסטר', 'חלב', 'milk'],
  'dairy/cheese/general': [
    'גבינ',
    'גבינה צהובה',
    'גבינת',
    'cheese',
    'מוצרלה',
    'פטה',
    'בולגרית',
    'קממבר',
    'ברי',
    'פרמזן',
    'מסקרפונה',
    'קוטג',
  ],
  'dairy/yogurt-desserts': [
    'יוגורט',
    'מעדן',
    'מעדנים',
    'דניאלה',
    'דנונה',
    'אקטימל',
    'yog',
    'pudding',
    'קפיר',
    'kefir',
    'אשל',
    'פרי-גן',
  ],
  'dairy/eggs': ['ביצי', 'ביצים', 'eggs', 'egg'],
  'dairy/butter-cream': [
    'חמאה',
    'butter',
    'שמנת',
    'cream',
    'sour cream',
    'cooking cream',
    'מסקרפונה',
    'קצפת',
    'whipping',
  ],
  // Plant-based milk + UHT/shelf-stable + coffee whitener all live in the
  // same "alternatives & shelf-stable" leaf in the 3-depth backbone.
  'dairy/milk/alternatives': [
    'משקה שקדים',
    'משקה סויה',
    'משקה שיבולת',
    'משקה קוקוס',
    'משקה אורז',
    'חלב סויה',
    'חלב שקדים',
    'חלב שיבולת',
    'חלב קוקוס',
    'חלב אורז',
    'סויה לבישול',
    'שמנת סויה',
    'אלפרו',
    'אומגה',
    'alpro',
    'oatly',
    'almond milk',
    'soy milk',
    'oat milk',
    'rice milk',
    'coconut milk',
    'plant-based',
    'plant based',
    'dairy free',
    'vegan',
    'טבעוני',
    'צמחי',
    'חלב עמיד',
    'מלבין קפה',
    'תחליף חלב',
    'תחליפי חלב',
    'uht',
    'shelf-stable',
  ],
  // Ready-to-drink milk-based and protein drinks (Rivion, drinkable yogurt,
  // Yotvata Pro, Go protein drinks, ready-to-drink coffee/latte).
  'dairy/milk/drinks': [
    'ריוויון',
    'שוקו',
    'משקה יוגורט',
    'משקה חלב',
    'משקה חלבון',
    'משקה פרוטאין',
    'מאסטר קפה',
    'יטבתה פרו',
    'גו לייט',
    'protein drink',
    'protein shake',
    'milk drink',
    'iced coffee',
    'latte',
    'cappuccino drink',
  ],
  // --- produce ---
  'produce/vegetables': [
    'ירק',
    'ירקות',
    'עגבני',
    'מלפפון',
    'בצל',
    'תפוח אדמה',
    'תפו"א',
    'גזר',
    'פלפל',
    'חס',
    'כרוב',
    'ברוקולי',
    'קישוא',
    'חציל',
    'דלעת',
    'vegetable',
    'tomato',
    'cucumber',
    'onion',
    'potato',
    'carrot',
    'lettuce',
    'cabbage',
    'broccoli',
    'eggplant',
  ],
  'produce/fruits': [
    'פרי',
    'פירות',
    'פיר ',
    'תפוח',
    'בננה',
    'תפוז',
    'אבוקדו',
    'תות',
    'ענב',
    'אבטיח',
    'מלון',
    'אגס',
    'נקטרינה',
    'אפרסק',
    'fruit',
    'apple',
    'banana',
    'orange',
    'avocado',
    'grape',
    'watermelon',
    'melon',
    'pear',
    'peach',
    'mango',
    'pineapple',
    'strawberry',
  ],
  'produce/herbs': [
    'עשבי תיבול',
    'תיבול טרי',
    'פטרוזיליה',
    'כוסברה',
    'בזיליקום',
    'נענע',
    'שמיר',
    'רוזמרין',
    'תימין',
    'herbs',
    'parsley',
    'cilantro',
    'basil',
    'mint',
    'dill',
    'rosemary',
    'thyme',
  ],
  'health-organic/organic-vegan': [
    'אורגני',
    'אורגנית',
    'organic',
    'bio',
    'biodynamic',
    'שופרסל גרין',
    'בריאות וטבע',
    'תזונה טבעית',
  ],
  // --- bakery ---
  'bakery/bread': [
    'לחם',
    'baguette',
    'בגט',
    'באגט',
    'בגטים',
    'באגטים',
    'לחמני',
    'לחמניה',
    'לחמניות',
    'טוסט',
    'פרוסות',
    'מוצרי מאפה',
    'bread',
    'loaf',
    'roll',
    'sliced bread',
  ],
  'bakery/pita-challah': [
    'פיתה',
    'פיתות',
    'חלה',
    'חלות',
    'בייגל',
    'בייגלה',
    'בייגלים',
    'לאפה',
    'לאפות',
    'bagel',
    'challah',
    'pita',
    'lafa',
  ],
  'bakery/pastries': [
    'מאפה',
    'מאפי',
    'בורקס',
    'קרואסון',
    'מאפים',
    'pastry',
    'croissant',
    'bourekas',
  ],
  'bakery/cakes-cookies': [
    'עוגה',
    'עוגי',
    'עוגות',
    'עוגיות',
    'cake',
    'cookie',
  ],
  'bakery/rolls-baguettes': [
    'בגט',
    'באגט',
    'בגטים',
    'באגטים',
    'לחמני',
    'לחמניה',
    'לחמניות',
    'baguette',
    'roll',
  ],
  // --- breakfast (kept top-level dept in new tree) ---
  'breakfast/cereals': [
    'דגני בוקר',
    'קורנפלקס',
    'גרנולה',
    'מוזלי',
    'שיבולת שועל',
    'cornflakes',
    'cereal',
    'granola',
    'oats',
    'oatmeal',
    'muesli',
    'cheerios',
  ],
  'pantry/sweet-spreads': [
    'ממרח',
    'ממרחים',
    'ריבה',
    'ריבת',
    'קונפיטורה',
    'נוטלה',
    'חמאת בוטנים',
    'שוקולד למריחה',
    'דבש',
    'סילאן',
    'סירופ מייפל',
    'jam',
    'spread',
    'preserves',
    'marmalade',
    'nutella',
    'peanut butter',
    'honey',
    'maple',
    'silan',
    'date syrup',
  ],
  // --- meat / fish ---
  'meat-fish/beef-lamb': [
    'בקר',
    'טלה',
    'כבש',
    'המבורגר',
    'אנטריקוט',
    'סינטה',
    'בשרים על האש',
    'בשר על האש',
    'מנגל',
    'beef',
    'lamb',
    'burger',
    'steak',
    'mince',
    'ground meat',
    'bbq',
  ],
  'meat-fish/poultry/general': [
    'עוף',
    'הודו',
    'שוק עוף',
    'חזה עוף',
    'כנפיים',
    'קציצ',
    'שניצל',
    'poultry',
    'chicken',
    'turkey',
    'schnitzel',
    'wing',
  ],
  'meat-fish/fish': [
    'דגים',
    'סלמון',
    'טונה',
    'דניס',
    'בקלה',
    'סרדינים',
    'אנשובי',
    'איקרה',
    'אקרה',
    'הרינג',
    'מתיאס',
    'fish',
    'salmon',
    'tuna',
    'cod',
    'sardine',
    'anchovy',
    'caviar',
    'roe',
    'herring',
  ],
  'meat-fish/deli-sausage': [
    'נקני',
    'נקניק',
    'נקניקיות',
    'פסטרמ',
    'סלמ',
    'frankfurter',
    'sausage',
    'salami',
    'pastrami',
    'hot dog',
    'frankfurter',
  ],
  // --- frozen ---
  'frozen/meals': [
    'ארוחה קפואה',
    'ארוחות קפואות',
    'פיצה קפואה',
    'frozen meal',
    'pizza',
    'מאפים קפואים',
  ],
  'frozen/ice-cream': ['גלידה', 'ארטיק', 'שלגון', 'ice cream', 'gelato', 'sorbet'],
  'frozen/vegetables-fries': ['ירקות קפואים', 'אפונה קפואה', 'צ\'יפס קפוא', 'frozen vegetables', 'frozen peas', 'frozen fries'],
  'frozen/meat-fish': ['דגים קפואים', 'עוף קפוא', 'בשר קפוא', 'frozen fish', 'frozen chicken', 'frozen meat'],
  // --- pantry ---
  'pantry/rice-pasta-legumes': [
    'אורז',
    'פסטה',
    'נודלס',
    'בורגול',
    'קוסקוס',
    'קטניות',
    'עדשים',
    'גרגרי חומוס',
    'שעועית יבשה',
    'מאש',
    'rice',
    'pasta',
    'noodle',
    'couscous',
    'spaghetti',
    'lentils',
    'chickpeas',
    'beans',
    'kidney',
  ],
  'pantry/oils-vinegar': [
    'שמן זית',
    'שמן קנולה',
    'שמן חמניות',
    'שמן',
    'חומץ',
    'מיץ לימון',
    'oil',
    'olive oil',
    'canola',
    'vinegar',
  ],
  'pantry/flour-sugar-baking': [
    'קמח',
    'סוכר',
    'אבקת אפיה',
    'שמרים',
    'אבקת סוכר',
    'flour',
    'sugar',
    'baking',
    'yeast',
    'powdered sugar',
  ],
  'pantry/spices': [
    'תבלין',
    'מלח',
    'פלפל שחור',
    'פפריקה',
    'כמון',
    'פרג',
    'spice',
    'salt',
    'pepper',
    'paprika',
    'cumin',
  ],
  'pantry/sauces': [
    'רוטב',
    'רטבים',
    'קטשופ',
    'מיונז',
    'חרדל',
    'רוטב סויה',
    'טחינה',
    'חומוס',
    'אמבה',
    'sauce',
    'ketchup',
    'mayonnaise',
    'mustard',
    'soy sauce',
    'tahini',
    'hummus',
    'amba',
  ],
  'pantry/canned': [
    'שימור',
    'שימורי',
    'תירס משומר',
    'אפונה משומרת',
    'תירס',
    'שעועית',
    'canned',
    'preserves',
    'corn',
  ],
  // --- snacks / sweets (new tree uses `snacks-sweets/...`) ---
  'snacks-sweets/salty': [
    'חטיף',
    'חטיפים',
    'במבה',
    'ביסלי',
    "צ'יפס",
    'תפוצ',
    'פופקורן',
    'פיצוחים',
    'crisps',
    'chips',
    'popcorn',
    'pretzel',
  ],
  'snacks-sweets/chocolate-candy': [
    'שוקולד',
    'פרלינים',
    'טבלת שוקולד',
    "kit kat",
    "snickers",
    "mars",
    'chocolate',
    'praline',
  ],
  'snacks-sweets/gum-candy': ['סוכריות', 'גומי', 'מנטוס', 'מסטיק', 'candy', 'gummy', 'jelly', 'mint', 'gum'],
  'snacks-sweets/cookies-wafers': [
    'ביסקויט',
    'ופל',
    'קרקר',
    'biscuit',
    'wafer',
    'cracker',
  ],
  'produce/dried-nuts': [
    'פירות יבשים',
    'אגוזים',
    'בוטנים',
    'שקדים',
    'קשיו',
    'פיסטוק',
    'תאנים',
    'תמרים',
    'צימוקים',
    'פיצוחים',
    'almond',
    'cashew',
    'pistachio',
    'raisin',
    'date',
    'fig',
    'nuts',
  ],
  // --- beverages ---
  'beverages/water-soda': ['מים מינרל', 'מים', 'נביעות', 'סודה', 'mineral water', 'spring water', 'sparkling', 'soda'],
  'beverages/soft-drinks': [
    'משקאות קלים',
    'משק קל',
    'קולה',
    'פפסי',
    'ספרייט',
    'פנטה',
    'soft drink',
    'cola',
    'pepsi',
    'sprite',
    'fanta',
    'soda',
  ],
  'beverages/juice-concentrates': [
    'מיץ',
    'תפוזינה',
    'משק פרי',
    'תרכיז',
    'תרכיזים',
    'juice',
    'orange juice',
    'apple juice',
    'concentrate',
    'syrup',
  ],
  'beverages/hot-drinks/coffee': [
    'קפה',
    'נס קפה',
    'אספרסו',
    'קפה נמס',
    'cappuccino',
    'coffee',
    'espresso',
    'instant coffee',
  ],
  'beverages/hot-drinks/tea': [
    'תה',
    'חליטה',
    'חליטות',
    'tea',
    'herbal tea',
  ],
  'beverages/hot-drinks/general': [
    'משקאות חמים',
    'משקה חם',
    'hot drink',
  ],
  'beverages/energy': [
    'משקה אנרגיה',
    'אנרגיה',
    'red bull',
    'monster',
    'xl',
    'energy drink',
    'isotonic',
  ],
  // --- alcohol ---
  'alcohol/beer': ['בירה', 'beer', 'lager', 'ale'],
  'alcohol/wine': ['יין', 'wine', 'cabernet', 'merlot', 'chardonnay', 'sauvignon'],
  'alcohol/spirits': [
    'וודקה',
    'ויסקי',
    'ערק',
    'גין',
    'רום',
    'טקילה',
    'ליקר',
    'spirits',
    'vodka',
    'whiskey',
    'whisky',
    'gin',
    'rum',
    'tequila',
    'liqueur',
    'arak',
    'cognac',
  ],
  // --- baby ---
  'baby/diapers-wipes': [
    'חיתול',
    'חיתולים',
    'טיטול',
    'טיטולים',
    'תחתוני ספיגה',
    'תחתוני',
    'ספיגה',
    'הרטבת לילה',
    'מגבונים לתינוק',
    'מגבונ',
    'pull-ups',
    'pull ups',
    'goodnites',
    'diaper',
    'pampers',
    'huggies',
    'האגיס',
    'libero',
    'training pants',
    'wipes',
    'baby wipes',
  ],
  'baby/baby-food': [
    'פורמולה',
    'מטרנה',
    'סימילאק',
    'נוטרילון',
    'מחית',
    'תחליף חלב',
    'מזון לתינוק',
    'אוכל לתינוק',
    'מזון לתינוקות',
    'formula',
    'baby food',
    'puree',
    'similac',
    'enfamil',
  ],
  'baby/baby-care': [
    'טיפוח תינוק',
    'אביזרי תינוק',
    'מוצרי ילדים',
    'מוצרי תינוק',
    'baby care',
    'baby accessories',
  ],
  // --- household ---
  'household/cleaning': [
    'ניקוי',
    'ניקיון',
    'חומר ניקוי',
    'אקונומיקה',
    'מלבין',
    'קוטל חרקים',
    'מבשם אויר',
    'מבשמי אויר',
    'מטליות',
    'מטלית',
    'מטליות לחות',
    'מטליות ניקוי',
    'סקוצ',
    'ספוג',
    'ספוגי',
    'מטאטא',
    'דלי',
    'מגב',
    'cleaning',
    'detergent',
    'bleach',
    'disinfectant',
    'multi-surface',
    'air freshener',
    'insecticide',
    'sponge',
    'mop',
    'squeegee',
    'wipes for floor',
    'floor wipes',
  ],
  'disposables/paper': [
    'נייר טואלט',
    'מגבת נייר',
    'מגבות נייר',
    'טישו',
    'מפיות',
    'מפית',
    'מגבונים יבשים',
    'toilet paper',
    'paper towel',
    'tissue',
    'napkin',
    'kleenex',
  ],
  'household/laundry': [
    'כביסה',
    'אבקת כביסה',
    'מרכך כביסה',
    'חדר כביסה',
    'אמבטיה וחדר כביסה',
    'laundry',
    'detergent',
    'fabric softener',
    'persil',
    'ariel',
  ],
  'home-kitchen/kitchen-utensils': [
    'כלי בית',
    'כלי מטבח',
    'נייר אפיה',
    'baking paper',
    'kitchenware',
    'household',
  ],
  'disposables/single-use': [
    'חד פעמי',
    'חד-פעמי',
    'כלים חד פעמיים',
    'single-use',
    'disposable',
  ],
  'disposables/bags-foil': [
    'אלומיניום',
    'נייר כסף',
    'שקיות',
    'שקיות זבל',
    'aluminum',
    'cling film',
    'foil',
    'plastic wrap',
    'trash bag',
  ],
  // --- personal-care ---
  'personal-care/hair/shampoo-conditioner': [
    'שמפו',
    'מרכך שיער',
    'shampoo',
    'conditioner',
  ],
  'personal-care/body': [
    'סבון',
    'גוף',
    'ג\'ל רחצה',
    'soap',
    'body wash',
    'shower gel',
  ],
  'personal-care/perfume-deodorant': [
    'דאודורנט',
    'בושם',
    'אנטיפרספירנט',
    'deodorant',
    'perfume',
    'antiperspirant',
  ],
  'personal-care/cosmetics': [
    'איפור',
    'מסקרה',
    'שפתון',
    'מייקאפ',
    'אודם',
    'lipstick',
    'mascara',
    'foundation',
    'cosmetic',
  ],
  'personal-care/oral': [
    'משחת שיניים',
    'מברשת שיניים',
    'מי פה',
    'שטיפת פה',
    'היגיינת הפה',
    'היגיינה אוראלית',
    'toothpaste',
    'toothbrush',
    'mouthwash',
    'oral',
    'dental',
  ],
  'personal-care/shaving': [
    'גילוח',
    'מכונת גילוח',
    'סכין גילוח',
    'אחרי גילוח',
    'הסרת שיער',
    'שעוות',
    'shaver',
    'razor',
    'shaving',
    'after shave',
    'wax',
    'hair removal',
  ],
  'personal-care/feminine': [
    'תחבושות',
    'טמפונים',
    'היגיינה נשית',
    'pads',
    'tampons',
    'feminine hygiene',
    'always',
    'tampax',
  ],
  // --- pet ---
  'pet/dog': ['כלב', 'כלבים', 'מזון לכלבים', 'מזון יבש לכלב', 'dog food', 'pedigree', 'royal canin'],
  'pet/cat': ['חתול', 'חתולים', 'מזון לחתולים', 'cat food', 'whiskas', 'kitten'],
};

/**
 * Group-level synonyms — used as a *fallback* when no leaf scores high
 * enough. Lets generic chain categories like "קפואים" (Frozen) map onto a
 * backbone GROUP id even when no specific leaf is a clear winner.
 */
export const GROUP_SYNONYMS: Readonly<Record<string, readonly string[]>> = {
  dairy: ['מוצרי חלב', 'חלב ומוצרי חלב', 'חלב, ביצים וסלטים', 'חלבי', 'dairy'],
  produce: [
    'פירות וירקות',
    'ירקות ופירות',
    'עולם הפירות',
    'עולם הפירות והירקות',
    'produce',
  ],
  bakery: ['מאפיה', 'מאפים', 'לחם ומאפים', 'bakery'],
  'meat-fish': [
    'בשר ודגים',
    'בשר, עוף ודגים',
    'בשר עוף ודגים',
    'בשר ועוף',
    'בשרים',
    'דגים',
    'meat',
    'fish',
  ],
  frozen: ['קפוא', 'קפואים', 'מוצרים קפואים', 'frozen'],
  pantry: [
    'מזווה',
    'מזון יבש',
    'יסודות מטבח',
    'יסודות',
    'מצרכי יסוד',
    'בישול ואפיה',
    'שימורים',
    'pantry',
    'staples',
  ],
  breakfast: ['דגני בוקר', 'ארוחת בוקר', 'cereal', 'breakfast'],
  'snacks-sweets': ['חטיפים', 'ממתקים', 'חטיפים וממתקים', 'snacks', 'sweets'],
  beverages: [
    'משקאות',
    'משקאות, אלכוהול',
    'משקאות, אלכוהול, יין וטבק',
    'משק קלים',
    'יין וטבק',
    'beverages',
    'drinks',
  ],
  alcohol: ['אלכוהול', 'משקאות חריפים', 'יין ואלכוהול', 'alcohol'],
  'health-organic': [
    'אורגני',
    'בריאות',
    'דיאטה',
    'בריאות וטבע',
    'organic',
    'health',
    'natural',
  ],
  baby: [
    'תינוקות',
    'מוצרי תינוקות',
    'פארם ותינוקות',
    'תינוקות וילדים',
    'baby',
  ],
  'personal-care': [
    'טיפוח',
    'טיפוח ויופי',
    'מוצרי פארם וטיפוח',
    'קוסמטיקה',
    'טיפוח אישי',
    'personal care',
  ],
  pharmacy: ['בית מרקחת', 'פארם', 'מוצרי פארם', 'תרופות', 'pharmacy', 'pharm'],
  household: [
    'ניקיון',
    'בית וניקיון',
    'הכל לבית',
    'אחזקת הבית',
    'אחזקת בית',
    'household',
  ],
  disposables: ['חד פעמי', 'חד-פעמי', 'נייר', 'מוצרי נייר', 'disposables'],
  'home-kitchen': [
    'כלי בית',
    'כלי מטבח',
    'ריהוט',
    'אביזרי בית',
    'home',
    'kitchenware',
  ],
  electronics: ['חשמל', 'אלקטרוניקה', 'מוצרי חשמל', 'electronics', 'appliance'],
  pet: ['חיות מחמד', 'בעלי חיים', 'בע"ח', 'pet'],
  'garden-outdoor': ['גינה', 'גן', 'חוץ', 'רכב', 'garden', 'outdoor', 'auto'],
  'kids-leisure': ['ילדים', 'פנאי', 'ביגוד', 'צעצועים', 'ספורט', 'kids', 'leisure', 'toys'],
  tobacco: ['טבק', 'סיגריות', 'tobacco', 'cigarettes'],
  promotions: ['מבצעים', 'מבצע', 'חגים', 'רשימות', 'promotion', 'sale'],
  other: ['שונות', 'אחר', 'כללי', 'other', 'misc'],
};

/**
 * Stop-words/phrases that appear in MANY chain category names but tell us
 * nothing about which leaf they belong to. We strip these before scoring.
 */
export const STOP_WORDS: ReadonlyArray<string> = [
  'מוצרי',
  'מוצר',
  'מותגים',
  'מותג',
  'בלעדי',
  'מבצעים',
  'מבצע',
  'חדש',
  'מומלץ',
  'אונליין',
  'תוצרת',
  'תוצרת חוץ',
  'תוצרת ישראל',
  'ל-',
  'ולל',
  'ולא',
  'מארז',
  'מארזים',
  'מבחר',
  'מבחר רחב',
  'הכל',
];
