/**
 * Shared types for the chain category scrapers.
 *
 * Each chain has its own native shape (Shufersal: 4-level alphanumeric codes;
 * Rami Levy: 3-level numeric ids with slugs). We capture them in a uniform
 * "ChainCategoryNode" tree to make downstream mapping/matching easier.
 */

export type ChainCategoryNode = {
  /** Stable per-chain id (string for Shufersal codes, numeric-string for Rami Levy). */
  id: string;
  /** Hebrew display name (canonical). */
  nameHe: string;
  /** Optional URL slug (Rami Levy only). */
  slug?: string;
  /** Public URL of the category landing page on the chain's website. */
  url?: string;
  /** Depth from the root (0 = department, 1 = group, 2 = subgroup, 3 = leaf). */
  depth: number;
  /** Children, in original sort order. */
  children: ChainCategoryNode[];
  /** Approximate product count if known. */
  productCount?: number;
};

export type ChainCategoryTree = {
  retailerSlug: 'shufersal' | 'rami-levy';
  retailerNameHe: string;
  scrapedAt: string;
  source: string;
  /** Top-level departments. */
  roots: ChainCategoryNode[];
  /** Total leaf count, useful for sanity-check logging. */
  leafCount: number;
};

/**
 * "Common" backbone the user-facing app uses.  Two levels deep:
 *   group  -> leaf
 * (Top-level groups are e.g. dairy/produce/meat; leaves are concrete shopper
 *  buckets like "milk", "yogurt", "cottage cheese", "eggs".)
 */
export type CommonCategoryNode = {
  id: string; // Stable slug, e.g. "dairy" or "dairy/milk".
  nameHe: string;
  nameEn: string;
  /** Lucide icon name shown in the nav (top-level only). */
  icon?: string;
  parentId?: string;
  children: CommonCategoryNode[];
};

export type CommonCategoryAlias = {
  /** Common backbone leaf id. */
  commonId: string;
  retailerSlug: 'shufersal' | 'rami-levy';
  /** Native chain category id (Shufersal code or Rami Levy id). */
  chainCategoryId: string;
  chainCategoryName: string;
  chainCategoryDepth: number;
  /** Confidence 0..1 from the matcher. */
  confidence: number;
  /** Best matching backbone synonym that fired. */
  matchedSynonym?: string;
  /** True if generated by the auto-matcher; false if added manually. */
  auto: boolean;
};

export type CommonTreeBuildResult = {
  builtAt: string;
  backbone: CommonCategoryNode[];
  aliases: CommonCategoryAlias[];
  unmapped: Array<{
    retailerSlug: 'shufersal' | 'rami-levy';
    chainCategoryId: string;
    chainCategoryName: string;
    chainCategoryDepth: number;
    /** Top three near-misses with their scores, for manual review. */
    nearMisses: Array<{ commonId: string; score: number }>;
  }>;
};
